Add check coverage report

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -38,6 +38,11 @@ jobs:
       run: |
         pytest --cov=TiMBA --cov-report xml:coverage.xml
 
+    # Ensure coverage.xml exists before uploading it
+    - name: Check coverage XML report
+      run: |
+        if [ ! -f coverage.xml ]; then echo "Coverage report not found!"; exit 1; fi
+
     # Upload the coverage XML report as an artifact
     - name: Upload coverage XML artifact
       uses: actions/upload-artifact@v4
